import type { AuthoredAction } from "./types.js";

type AuthoredActionShapeKeys = {
  readonly [Kind in AuthoredAction["kind"]]: readonly Extract<keyof Extract<AuthoredAction, { kind: Kind }>, string>[];
};

export const AUTHORED_ACTION_SHAPE_KEYS: Readonly<Record<string, readonly string[]>> = {
  "workspace-bootstrap": ["kind", "workspaceNodeId"],
  "node-create": ["kind", "nodeId", "ownerNodeId", "originalPlacement", "intrinsicNodeType", "seed"],
  "node-trash": ["kind", "nodeId"],
  "node-restore": ["kind", "nodeId", "placementId", "parentNodeId", "anchor"],
  "original-promote": ["kind", "nodeId", "placementId"],
  "placement-create": ["kind", "placementId", "nodeId", "parentNodeId", "anchor"],
  "placement-remove": ["kind", "placementId"],
  "placement-move": ["kind", "placementId", "parentNodeId", "anchor"],
  "supertag-application-add": ["kind", "hostNodeId", "supertagId", "anchor"],
  "supertag-membership-remove": ["kind", "hostNodeId", "supertagId"],
  "supertag-extension-add": ["kind", "supertagId", "baseSupertagId", "anchor"],
  "supertag-extension-remove": ["kind", "supertagId", "baseSupertagId"],
  "template-member-add": ["kind", "supertagId", "templateNodeId", "anchor"],
  "template-member-remove": ["kind", "supertagId", "templateNodeId"],
  "template-field-add": ["kind", "supertagId", "fieldDefinition", "anchor"],
  "template-field-remove": ["kind", "supertagId", "fieldDefinitionId"],
  "template-field-restore": ["kind", "templateFieldId"],
  "template-field-visibility-set": ["kind", "templateFieldId", "visibility"],
  "template-field-static-default-set": ["kind", "templateFieldId", "value"],
  "optional-field-contribution-add": ["kind", "supertagId", "fieldDefinitionId", "anchor"],
  "optional-field-contribution-remove": ["kind", "supertagId", "fieldDefinitionId"],
  "template-node-detach": ["kind", "ownerNodeId", "templateNodeId", "instanceNodeId", "instanceOccurrenceId", "anchor"],
  "field-materialize": ["kind", "ownerNodeId", "fieldDefinitionId", "fieldNodeId", "fieldOccurrenceId"],
  "field-value-remove": ["kind", "valuePlacementId"],
  "materialized-field-clear": ["kind", "ownerNodeId", "fieldDefinitionId"],
  "field-configuration-set": ["kind", "fieldDefinitionId", "configuration"],
  "field-definition-make-discoverable": ["kind", "fieldDefinitionId"],
  "field-definition-return-to-template-field": ["kind", "fieldDefinitionId", "templateFieldId"],
  "rich-text-splice": ["kind", "nodeId", "deleteAtomIds", "anchor", "insert", "attributes"],
  "rich-text-mark": ["kind", "nodeId", "atomIds", "key", "value"],
  "inline-reference-create": ["kind", "inlineReferenceId", "hostNodeId", "targetNodeId", "anchor"],
  "inline-reference-remove": ["kind", "inlineReferenceId"],
  "inline-alias-attach": ["kind", "inlineReferenceId", "aliasNodeId"],
  "inline-alias-detach": ["kind", "inlineReferenceId", "aliasNodeId"],
  "search-expression-add": ["kind", "expressionHostId", "parentExpressionId", "clause", "anchor"],
  "search-expression-configure": ["kind", "expressionId", "clause"],
  "search-expression-move": ["kind", "expressionId", "parentExpressionId", "anchor"],
  "search-expression-remove": ["kind", "expressionId"],
  "search-expression-restore": ["kind", "expressionId"],
  "shared-default-view-add": ["kind", "hostNodeId", "viewType", "anchor"],
  "shared-default-view-remove": ["kind", "hostNodeId"],
  "shared-default-view-restore": ["kind", "viewId"],
  "view-mode-set": ["kind", "viewId", "viewType"],
  "view-column-add": ["kind", "viewId", "fieldDefinitionId", "anchor"],
  "view-column-remove": ["kind", "viewId", "fieldDefinitionId"],
  "view-column-move": ["kind", "columnId", "anchor"],
  "view-sort-add": ["kind", "viewId", "fieldDefinitionId", "direction"],
  "view-sort-configure": ["kind", "sortId", "fieldDefinitionId", "direction"],
  "view-sort-remove": ["kind", "viewId"],
  "view-sort-restore": ["kind", "sortId"],
  "view-group-add": ["kind", "viewId", "fieldDefinitionId"],
  "view-group-remove": ["kind", "viewId"],
  "view-filter-add": ["kind", "viewId"],
  "view-filter-remove": ["kind", "viewId"],
  "view-filter-restore": ["kind", "filterId"],
} satisfies AuthoredActionShapeKeys;
