import type { Mutation } from "./types.js";

type MutationShapeKeys = {
  readonly [Kind in Mutation["kind"]]: readonly Extract<keyof Extract<Mutation, { kind: Kind }>, string>[];
};

export const MUTATION_SHAPE_KEYS: Readonly<Record<string, readonly string[]>> = {
  "node-create": ["kind", "nodeId", "seed"],
  "node-delete": ["kind", "nodeId"],
  "node-restore": ["kind", "nodeId", "deletionFactId"],
  "occurrence-create": ["kind", "occurrenceId", "nodeId", "parentNodeId", "anchor"],
  "occurrence-delete": ["kind", "occurrenceId", "previousParentNodeId", "previousAnchor"],
  "occurrence-restore": ["kind", "occurrenceId", "deletionFactId", "parentNodeId", "anchor"],
  "occurrence-move": ["kind", "occurrenceId", "parentNodeId", "anchor", "previousParentNodeId", "previousAnchor"],
  "node-owner-set": ["kind", "nodeId", "ownerNodeId", "previousOwnerNodeId"],
  "node-type-declare": ["kind", "nodeId", "nodeType"],
  "schema-apply": ["kind", "nodeId", "schemaId", "anchor"],
  "schema-remove": ["kind", "nodeId", "schemaId", "previousAnchor"],
  "schema-field-add": ["kind", "schemaId", "fieldDefinitionId", "fieldNodeId", "fieldOccurrenceId", "anchor"],
  "schema-field-remove": [
    "kind",
    "schemaId",
    "fieldDefinitionId",
    "fieldNodeId",
    "fieldOccurrenceId",
    "previousAnchor",
  ],
  "schema-field-configure": [
    "kind",
    "schemaId",
    "fieldDefinitionId",
    "fieldNodeId",
    "config",
    "previousConfig",
    "observedConfigFactIds",
  ],
  "schema-extension-add": ["kind", "schemaId", "baseSchemaId", "anchor"],
  "schema-extension-remove": ["kind", "schemaId", "baseSchemaId", "previousAnchor"],
  "schema-template-node-add": ["kind", "schemaId", "templateNodeId", "templateOccurrenceId", "anchor"],
  "schema-template-node-remove": ["kind", "schemaId", "templateNodeId", "templateOccurrenceId", "previousAnchor"],
  "template-node-detach": [
    "kind",
    "ownerNodeId",
    "templateNodeId",
    "instanceNodeId",
    "instanceOccurrenceId",
    "anchor",
    "sourceSchemaIds",
    "sourceApplicationSchemaIds",
    "sourceTemplateOccurrenceIds",
  ],
  "field-materialize": ["kind", "ownerNodeId", "fieldDefinitionId", "fieldNodeId", "fieldOccurrenceId"],
  "field-value-delete": [
    "kind",
    "ownerNodeId",
    "fieldDefinitionId",
    "valueOccurrenceId",
    "previousParentNodeId",
    "previousAnchor",
  ],
  "materialized-field-delete": [
    "kind",
    "ownerNodeId",
    "fieldDefinitionId",
    "fieldNodeId",
    "fieldOccurrenceId",
    "previousParentNodeId",
    "previousAnchor",
  ],
  "field-initialize": [
    "kind",
    "ownerNodeId",
    "schemaId",
    "fieldDefinitionId",
    "fieldNodeId",
    "fieldOccurrenceId",
    "source",
    "values",
    "observedInitializationFactIds",
  ],
  "text-splice": ["kind", "nodeId", "deleteAtomIds", "deletedAtoms", "anchor", "insert", "attributes"],
  "text-mark": ["kind", "nodeId", "atomIds", "key", "value", "previous"],
  "value-set": ["kind", "target", "namespace", "key", "value", "previous"],
  "value-unset": ["kind", "target", "namespace", "key", "previous"],
} satisfies MutationShapeKeys;
