import type { Mutation } from "./types.js";

type MutationShapeKeys = {
  readonly [Kind in Mutation["kind"]]: readonly Extract<keyof Extract<Mutation, { kind: Kind }>, string>[];
};

export const MUTATION_SHAPE_KEYS: Readonly<Record<string, readonly string[]>> = {
  "node-create": ["kind", "nodeId", "seed"],
  "node-delete": ["kind", "nodeId"],
  "node-restore": ["kind", "nodeId", "deletionFactId"],
  "occurrence-create": ["kind", "occurrenceId", "nodeId", "parentNodeId", "anchor"],
  "occurrence-delete": ["kind", "occurrenceId", "previousParentNodeId", "previousAnchor"],
  "occurrence-restore": ["kind", "occurrenceId", "deletionFactId", "parentNodeId", "anchor"],
  "occurrence-move": ["kind", "occurrenceId", "parentNodeId", "anchor", "previousParentNodeId", "previousAnchor"],
  "node-owner-set": ["kind", "nodeId", "ownerNodeId", "previousOwnerNodeId"],
  "metanode-attach": ["kind", "hostNodeId", "metanodeId"],
  "node-type-declare": ["kind", "nodeId", "nodeType"],
  "supertag-apply": ["kind", "nodeId", "supertagId", "anchor"],
  "supertag-remove": ["kind", "nodeId", "supertagId", "previousAnchor"],
  "supertag-field-add": ["kind", "supertagId", "fieldDefinitionId", "fieldNodeId", "fieldOccurrenceId", "anchor"],
  "supertag-field-remove": [
    "kind",
    "supertagId",
    "fieldDefinitionId",
    "fieldNodeId",
    "fieldOccurrenceId",
    "previousAnchor",
  ],
  "supertag-field-configure": [
    "kind",
    "supertagId",
    "fieldDefinitionId",
    "fieldNodeId",
    "config",
    "previousConfig",
    "observedConfigFactIds",
  ],
  "supertag-extension-add": ["kind", "supertagId", "baseSupertagId", "anchor"],
  "supertag-extension-remove": ["kind", "supertagId", "baseSupertagId", "previousAnchor"],
  "supertag-template-node-add": ["kind", "supertagId", "templateNodeId", "templateOccurrenceId", "anchor"],
  "supertag-template-node-remove": ["kind", "supertagId", "templateNodeId", "templateOccurrenceId", "previousAnchor"],
  "template-node-detach": [
    "kind",
    "ownerNodeId",
    "templateNodeId",
    "instanceNodeId",
    "instanceOccurrenceId",
    "anchor",
    "sourceSupertagIds",
    "sourceApplicationSupertagIds",
    "sourceTemplateOccurrenceIds",
  ],
  "field-materialize": ["kind", "ownerNodeId", "fieldDefinitionId", "fieldNodeId", "fieldOccurrenceId"],
  "field-value-delete": [
    "kind",
    "ownerNodeId",
    "fieldDefinitionId",
    "valueOccurrenceId",
    "previousParentNodeId",
    "previousAnchor",
  ],
  "materialized-field-delete": [
    "kind",
    "ownerNodeId",
    "fieldDefinitionId",
    "fieldNodeId",
    "fieldOccurrenceId",
    "previousParentNodeId",
    "previousAnchor",
  ],
  "field-initialize": [
    "kind",
    "ownerNodeId",
    "supertagId",
    "fieldDefinitionId",
    "fieldNodeId",
    "fieldOccurrenceId",
    "source",
    "values",
    "observedInitializationFactIds",
  ],
  "field-datatype-configure": [
    "kind",
    "fieldDefinitionId",
    "configurationNodeId",
    "configurationOccurrenceId",
    "datatype",
    "previousDatatype",
    "observedValueFactIds",
  ],
  "field-cardinality-configure": [
    "kind",
    "fieldDefinitionId",
    "configurationNodeId",
    "configurationOccurrenceId",
    "cardinality",
    "previousCardinality",
    "observedValueFactIds",
  ],
  "field-initialization-expression-configure": [
    "kind",
    "fieldDefinitionId",
    "configurationNodeId",
    "configurationOccurrenceId",
    "expression",
    "previousExpression",
    "observedValueFactIds",
  ],
  "text-splice": ["kind", "nodeId", "deleteAtomIds", "deletedAtoms", "anchor", "insert", "attributes"],
  "text-mark": ["kind", "nodeId", "atomIds", "key", "value", "previous"],
  "inline-reference-create": ["kind", "inlineReferenceId", "hostNodeId", "targetNodeId", "anchor"],
  "inline-reference-delete": [
    "kind",
    "inlineReferenceId",
    "previousHostNodeId",
    "previousTargetNodeId",
    "previousAnchor",
  ],
  "inline-reference-alias-attach": ["kind", "inlineReferenceId", "aliasNodeId"],
  "inline-reference-alias-detach": ["kind", "inlineReferenceId", "aliasNodeId"],
  "search-supertag-clause-attach": ["kind", "searchNodeId", "clauseNodeId", "clauseOccurrenceId", "supertagId"],
  "search-field-clause-attach": ["kind", "searchNodeId", "clauseNodeId", "clauseOccurrenceId", "fieldDefinitionId"],
  "shared-default-view-definition-attach": ["kind", "hostNodeId", "viewDefinitionNodeId", "viewDefinitionOccurrenceId"],
  "shared-default-view-definition-mode-set": [
    "kind",
    "viewDefinitionNodeId",
    "viewType",
    "previousViewType",
    "observedModeFactIds",
  ],
} satisfies MutationShapeKeys;
