import type { Mutation } from "./types.js";

type MutationShapeKeys = {
  readonly [Kind in Mutation["kind"]]: readonly Extract<keyof Extract<Mutation, { kind: Kind }>, string>[];
};

export const MUTATION_SHAPE_KEYS: Readonly<Record<string, readonly string[]>> = {
  "node-create": ["kind", "nodeId", "seed"],
  "node-delete": ["kind", "nodeId"],
  "node-restore": ["kind", "nodeId", "deletionFactId"],
  "occurrence-create": ["kind", "occurrenceId", "nodeId", "parentNodeId", "anchor"],
  "occurrence-delete": ["kind", "occurrenceId", "previousParentNodeId", "previousAnchor"],
  "occurrence-restore": ["kind", "occurrenceId", "deletionFactId", "parentNodeId", "anchor"],
  "occurrence-move": ["kind", "occurrenceId", "parentNodeId", "anchor", "previousParentNodeId", "previousAnchor"],
  "node-owner-set": ["kind", "nodeId", "ownerNodeId", "previousOwnerNodeId"],
  "metanode-attach": ["kind", "hostNodeId", "metanodeId"],
  "intrinsic-node-type-declare": ["kind", "nodeId", "intrinsicNodeType"],
  "supertag-apply": [
    "kind",
    "hostNodeId",
    "supertagId",
    "applicationNodeId",
    "applicationOccurrenceId",
    "relationDefinitionOccurrenceId",
    "definitionOccurrenceId",
    "anchor",
  ],
  "supertag-remove": [
    "kind",
    "hostNodeId",
    "supertagId",
    "applicationNodeId",
    "applicationOccurrenceId",
    "relationDefinitionOccurrenceId",
    "definitionOccurrenceId",
    "detachedValueNodeId",
    "detachedValueOccurrenceId",
    "previousAnchor",
  ],
  "supertag-extension-add": ["kind", "supertagId", "baseSupertagId", "anchor"],
  "supertag-extension-remove": ["kind", "supertagId", "baseSupertagId", "previousAnchor"],
  "supertag-template-node-add": ["kind", "supertagId", "templateNodeId", "templateOccurrenceId", "anchor"],
  "supertag-template-node-remove": ["kind", "supertagId", "templateNodeId", "templateOccurrenceId", "previousAnchor"],
  "supertag-template-field-attach": [
    "kind",
    "supertagId",
    "templateFieldNodeId",
    "templateFieldOccurrenceId",
    "fieldDefinitionId",
    "definitionOccurrenceId",
    "staticDefaultValueNodeId",
    "staticDefaultValueOccurrenceId",
    "anchor",
  ],
  "supertag-template-field-existing-attach": [
    "kind",
    "supertagId",
    "templateFieldNodeId",
    "templateFieldOccurrenceId",
    "fieldDefinitionId",
    "definitionOccurrenceId",
    "staticDefaultValueNodeId",
    "staticDefaultValueOccurrenceId",
    "anchor",
  ],
  "supertag-template-field-detach": [
    "kind",
    "supertagId",
    "templateFieldNodeId",
    "templateFieldOccurrenceId",
    "fieldDefinitionId",
    "definitionOccurrenceId",
    "staticDefaultValueNodeId",
    "staticDefaultValueOccurrenceId",
    "previousAnchor",
  ],
  "supertag-template-field-discoverability-set": [
    "kind",
    "supertagId",
    "templateFieldNodeId",
    "fieldDefinitionId",
    "discoverable",
    "previousDiscoverable",
  ],
  "supertag-template-field-visibility-configure": [
    "kind",
    "supertagId",
    "templateFieldNodeId",
    "fieldDefinitionId",
    "visibility",
    "previousVisibility",
    "observedVisibilityFactIds",
  ],
  "supertag-optional-field-contribution-attach": [
    "kind",
    "supertagId",
    "fieldNurseryNodeId",
    "fieldNurseryOccurrenceId",
    "nurseryDefinitionOccurrenceId",
    "nurseryValueNodeId",
    "nurseryValueOccurrenceId",
    "contributionNodeId",
    "contributionOccurrenceId",
    "fieldDefinitionId",
    "definitionOccurrenceId",
    "valueNodeId",
    "valueOccurrenceId",
    "anchor",
  ],
  "supertag-optional-field-contribution-detach": [
    "kind",
    "supertagId",
    "fieldNurseryNodeId",
    "fieldNurseryOccurrenceId",
    "nurseryDefinitionOccurrenceId",
    "nurseryValueNodeId",
    "nurseryValueOccurrenceId",
    "contributionNodeId",
    "contributionOccurrenceId",
    "fieldDefinitionId",
    "definitionOccurrenceId",
    "valueNodeId",
    "valueOccurrenceId",
    "previousAnchor",
  ],
  "template-node-detach": [
    "kind",
    "ownerNodeId",
    "templateNodeId",
    "instanceNodeId",
    "instanceOccurrenceId",
    "anchor",
    "sourceSupertagIds",
    "sourceApplicationSupertagIds",
    "sourceTemplateOccurrenceIds",
  ],
  "field-materialize": ["kind", "ownerNodeId", "fieldDefinitionId", "fieldNodeId", "fieldOccurrenceId"],
  "field-value-delete": [
    "kind",
    "ownerNodeId",
    "fieldDefinitionId",
    "valueOccurrenceId",
    "previousParentNodeId",
    "previousAnchor",
  ],
  "materialized-field-delete": [
    "kind",
    "ownerNodeId",
    "fieldDefinitionId",
    "fieldNodeId",
    "fieldOccurrenceId",
    "previousParentNodeId",
    "previousAnchor",
  ],
  "field-datatype-configure": [
    "kind",
    "fieldDefinitionId",
    "configurationNodeId",
    "configurationOccurrenceId",
    "datatypeNodeId",
    "previousDatatypeNodeId",
    "observedValueFactIds",
  ],
  "field-cardinality-configure": [
    "kind",
    "fieldDefinitionId",
    "configurationNodeId",
    "configurationOccurrenceId",
    "cardinalityNodeId",
    "previousCardinalityNodeId",
    "observedValueFactIds",
  ],
  "field-optionality-configure": [
    "kind",
    "fieldDefinitionId",
    "configurationNodeId",
    "configurationOccurrenceId",
    "optionalityNodeId",
    "previousOptionalityNodeId",
    "observedValueFactIds",
  ],
  "field-initialization-expression-configure": [
    "kind",
    "fieldDefinitionId",
    "configurationNodeId",
    "configurationOccurrenceId",
    "expression",
    "previousExpression",
    "observedValueFactIds",
  ],
  "text-splice": ["kind", "nodeId", "deleteAtomIds", "deletedAtoms", "anchor", "insert", "attributes"],
  "text-mark": ["kind", "nodeId", "atomIds", "key", "value", "previous"],
  "inline-reference-create": ["kind", "inlineReferenceId", "hostNodeId", "targetNodeId", "anchor"],
  "inline-reference-delete": [
    "kind",
    "inlineReferenceId",
    "previousHostNodeId",
    "previousTargetNodeId",
    "previousAnchor",
  ],
  "inline-reference-alias-attach": ["kind", "inlineReferenceId", "aliasNodeId"],
  "inline-reference-alias-detach": ["kind", "inlineReferenceId", "aliasNodeId"],
  "search-expression-attach": [
    "kind",
    "searchNodeId",
    "expressionNodeId",
    "expressionOccurrenceId",
    "definitionOccurrenceId",
    "expression",
    "previousExpression",
  ],
  "search-expression-detach": [
    "kind",
    "searchNodeId",
    "expressionNodeId",
    "expressionOccurrenceId",
    "definitionOccurrenceId",
    "expression",
  ],
  "shared-default-view-definition-attach": [
    "kind",
    "hostNodeId",
    "attachmentNodeId",
    "attachmentOccurrenceId",
    "relationDefinitionOccurrenceId",
    "viewDefinitionNodeId",
    "viewDefinitionOccurrenceId",
  ],
  "shared-default-view-definition-detach": [
    "kind",
    "hostNodeId",
    "attachmentNodeId",
    "attachmentOccurrenceId",
    "relationDefinitionOccurrenceId",
    "viewDefinitionNodeId",
    "viewDefinitionOccurrenceId",
    "detachedValueNodeId",
    "detachedValueOccurrenceId",
  ],
  "shared-default-view-definition-mode-set": [
    "kind",
    "viewDefinitionNodeId",
    "viewType",
    "previousViewType",
    "observedModeFactIds",
  ],
  "shared-default-view-definition-sort-by-name-set": [
    "kind",
    "hostNodeId",
    "viewDefinitionNodeId",
    "sortOrderFieldNodeId",
    "sortOrderFieldOccurrenceId",
    "sortFieldNodeId",
    "sortFieldOccurrenceId",
    "nodeNameOccurrenceId",
    "ascendingOccurrenceId",
    "enabled",
    "previousEnabled",
  ],
  "shared-default-view-definition-options-set": [
    "kind",
    "hostNodeId",
    "viewDefinitionNodeId",
    "options",
    "previousOptions",
    "observedOptionsFactIds",
  ],
} satisfies MutationShapeKeys;
