import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: { backgroundColor: '#0b1110', flex: 1 },
  content: { flexGrow: 1, paddingHorizontal: 24 },
  eyebrow: {
    color: '#82c9a5',
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 1.8,
  },
  title: { color: '#f4f7f5', fontSize: 34, fontWeight: '700', marginTop: 10 },
  intro: { color: '#a6b3ad', fontSize: 17, lineHeight: 25, marginTop: 16 },
  statusCard: {
    backgroundColor: '#121c19',
    borderColor: '#263a33',
    borderRadius: 18,
    borderWidth: 1,
    marginTop: 28,
    padding: 20,
  },
  statusHeading: { alignItems: 'center', flexDirection: 'row', gap: 10 },
  statusDot: { borderRadius: 6, height: 12, width: 12 },
  statusReady: { backgroundColor: '#67d498' },
  statusLocked: { backgroundColor: '#efc66c' },
  statusStarting: { backgroundColor: '#78928a' },
  statusTitle: { color: '#e6eee9', fontSize: 19, fontWeight: '600' },
  statusDetail: { color: '#8fa099', fontSize: 14, marginTop: 10 },
  form: { gap: 18, marginTop: 24 },
  label: { color: '#bac7c1', fontSize: 14, fontWeight: '600', marginBottom: 8 },
  input: {
    backgroundColor: '#111a18',
    borderColor: '#2b3e37',
    borderRadius: 13,
    borderWidth: 1,
    color: '#f4f7f5',
    fontSize: 17,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  button: {
    alignItems: 'center',
    backgroundColor: '#86dbae',
    borderRadius: 13,
    minHeight: 52,
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  buttonPressed: { backgroundColor: '#70c99a' },
  buttonDisabled: { opacity: 0.65 },
  buttonText: { color: '#0d1713', fontSize: 17, fontWeight: '700' },
  readyCard: {
    backgroundColor: '#13221d',
    borderColor: '#2d5945',
    borderRadius: 18,
    borderWidth: 1,
    marginTop: 24,
    padding: 22,
  },
  readyTitle: { color: '#eaf7ef', fontSize: 22, fontWeight: '700' },
  readyDetail: {
    color: '#a4baaf',
    fontSize: 15,
    lineHeight: 22,
    marginTop: 10,
  },
  error: {
    backgroundColor: '#2a1617',
    borderColor: '#633438',
    borderRadius: 12,
    borderWidth: 1,
    color: '#ffb2b6',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 20,
    padding: 14,
  },
  engineHost: { height: 1, opacity: 0.01, position: 'absolute', width: 1 },
});
