import { FactActionKind as ProtocolFactActionKind } from "@lode/protocol/dto/review";
import { defineProtocolEnum, type DomainEnum } from "./enum-codec.js";

export const factActionKind = defineProtocolEnum<ProtocolFactActionKind>()(
  {
    [ProtocolFactActionKind.FACT_ACTION_KIND_UNSPECIFIED]: null,
    [ProtocolFactActionKind.FACT_ACTION_KIND_WORKSPACE_BOOTSTRAP]: "workspace-bootstrap",
    [ProtocolFactActionKind.FACT_ACTION_KIND_NODE_CREATE]: "node-create",
    [ProtocolFactActionKind.FACT_ACTION_KIND_NODE_TRASH]: "node-trash",
    [ProtocolFactActionKind.FACT_ACTION_KIND_NODE_RESTORE]: "node-restore",
    [ProtocolFactActionKind.FACT_ACTION_KIND_ORIGINAL_PROMOTE]: "original-promote",
    [ProtocolFactActionKind.FACT_ACTION_KIND_PLACEMENT_CREATE]: "placement-create",
    [ProtocolFactActionKind.FACT_ACTION_KIND_PLACEMENT_REMOVE]: "placement-remove",
    [ProtocolFactActionKind.FACT_ACTION_KIND_PLACEMENT_MOVE]: "placement-move",
    [ProtocolFactActionKind.FACT_ACTION_KIND_SUPERTAG_APPLICATION_ADD]: "supertag-application-add",
    [ProtocolFactActionKind.FACT_ACTION_KIND_SUPERTAG_MEMBERSHIP_REMOVE]: "supertag-membership-remove",
    [ProtocolFactActionKind.FACT_ACTION_KIND_SUPERTAG_EXTENSION_ADD]: "supertag-extension-add",
    [ProtocolFactActionKind.FACT_ACTION_KIND_SUPERTAG_EXTENSION_REMOVE]: "supertag-extension-remove",
    [ProtocolFactActionKind.FACT_ACTION_KIND_TEMPLATE_MEMBER_ADD]: "template-member-add",
    [ProtocolFactActionKind.FACT_ACTION_KIND_TEMPLATE_MEMBER_REMOVE]: "template-member-remove",
    [ProtocolFactActionKind.FACT_ACTION_KIND_TEMPLATE_NODE_DETACH]: "template-node-detach",
    [ProtocolFactActionKind.FACT_ACTION_KIND_FIELD_MATERIALIZE]: "field-materialize",
    [ProtocolFactActionKind.FACT_ACTION_KIND_FIELD_VALUE_REMOVE]: "field-value-remove",
    [ProtocolFactActionKind.FACT_ACTION_KIND_MATERIALIZED_FIELD_CLEAR]: "materialized-field-clear",
    [ProtocolFactActionKind.FACT_ACTION_KIND_RICH_TEXT_SPLICE]: "rich-text-splice",
    [ProtocolFactActionKind.FACT_ACTION_KIND_RICH_TEXT_MARK]: "rich-text-mark",
    [ProtocolFactActionKind.FACT_ACTION_KIND_INLINE_REFERENCE_CREATE]: "inline-reference-create",
    [ProtocolFactActionKind.FACT_ACTION_KIND_INLINE_REFERENCE_REMOVE]: "inline-reference-remove",
    [ProtocolFactActionKind.FACT_ACTION_KIND_INLINE_ALIAS_ATTACH]: "inline-alias-attach",
    [ProtocolFactActionKind.FACT_ACTION_KIND_INLINE_ALIAS_DETACH]: "inline-alias-detach",
    [ProtocolFactActionKind.FACT_ACTION_KIND_SEARCH_EXPRESSION_ADD]: "search-expression-add",
    [ProtocolFactActionKind.FACT_ACTION_KIND_SEARCH_EXPRESSION_CONFIGURE]: "search-expression-configure",
    [ProtocolFactActionKind.FACT_ACTION_KIND_SEARCH_EXPRESSION_MOVE]: "search-expression-move",
    [ProtocolFactActionKind.FACT_ACTION_KIND_SEARCH_EXPRESSION_REMOVE]: "search-expression-remove",
    [ProtocolFactActionKind.FACT_ACTION_KIND_SEARCH_EXPRESSION_RESTORE]: "search-expression-restore",
    [ProtocolFactActionKind.FACT_ACTION_KIND_SHARED_DEFAULT_VIEW_ADD]: "shared-default-view-add",
    [ProtocolFactActionKind.FACT_ACTION_KIND_SHARED_DEFAULT_VIEW_REMOVE]: "shared-default-view-remove",
    [ProtocolFactActionKind.FACT_ACTION_KIND_SHARED_DEFAULT_VIEW_RESTORE]: "shared-default-view-restore",
    [ProtocolFactActionKind.FACT_ACTION_KIND_VIEW_MODE_SET]: "view-mode-set",
    [ProtocolFactActionKind.FACT_ACTION_KIND_VIEW_COLUMN_ADD]: "view-column-add",
    [ProtocolFactActionKind.FACT_ACTION_KIND_VIEW_COLUMN_REMOVE]: "view-column-remove",
    [ProtocolFactActionKind.FACT_ACTION_KIND_VIEW_COLUMN_MOVE]: "view-column-move",
    [ProtocolFactActionKind.FACT_ACTION_KIND_VIEW_SORT_ADD]: "view-sort-add",
    [ProtocolFactActionKind.FACT_ACTION_KIND_VIEW_SORT_CONFIGURE]: "view-sort-configure",
    [ProtocolFactActionKind.FACT_ACTION_KIND_VIEW_SORT_REMOVE]: "view-sort-remove",
    [ProtocolFactActionKind.FACT_ACTION_KIND_VIEW_SORT_RESTORE]: "view-sort-restore",
    [ProtocolFactActionKind.FACT_ACTION_KIND_VIEW_GROUP_ADD]: "view-group-add",
    [ProtocolFactActionKind.FACT_ACTION_KIND_VIEW_GROUP_REMOVE]: "view-group-remove",
    [ProtocolFactActionKind.FACT_ACTION_KIND_VIEW_FILTER_ADD]: "view-filter-add",
    [ProtocolFactActionKind.FACT_ACTION_KIND_VIEW_FILTER_REMOVE]: "view-filter-remove",
    [ProtocolFactActionKind.FACT_ACTION_KIND_VIEW_FILTER_RESTORE]: "view-filter-restore",
    [ProtocolFactActionKind.FACT_ACTION_KIND_FIELD_CONFIGURATION_SET]: "field-configuration-set",
    [ProtocolFactActionKind.FACT_ACTION_KIND_TEMPLATE_FIELD_ADD]: "template-field-add",
    [ProtocolFactActionKind.FACT_ACTION_KIND_TEMPLATE_FIELD_REMOVE]: "template-field-remove",
    [ProtocolFactActionKind.FACT_ACTION_KIND_TEMPLATE_FIELD_RESTORE]: "template-field-restore",
    [ProtocolFactActionKind.FACT_ACTION_KIND_TEMPLATE_FIELD_VISIBILITY_SET]: "template-field-visibility-set",
    [ProtocolFactActionKind.FACT_ACTION_KIND_TEMPLATE_FIELD_STATIC_DEFAULT_SET]: "template-field-static-default-set",
    [ProtocolFactActionKind.FACT_ACTION_KIND_OPTIONAL_FIELD_CONTRIBUTION_ADD]: "optional-field-contribution-add",
    [ProtocolFactActionKind.FACT_ACTION_KIND_OPTIONAL_FIELD_CONTRIBUTION_REMOVE]: "optional-field-contribution-remove",
    [ProtocolFactActionKind.FACT_ACTION_KIND_FIELD_DEFINITION_MAKE_DISCOVERABLE]: "field-definition-make-discoverable",
    [ProtocolFactActionKind.FACT_ACTION_KIND_FIELD_DEFINITION_RETURN_TO_TEMPLATE_FIELD]:
      "field-definition-return-to-template-field",
    [ProtocolFactActionKind.UNRECOGNIZED]: null,
  },
  "Fact action kind",
);
export type FactActionKind = DomainEnum<typeof factActionKind>;
