import type { AuthoredAction } from "../../src/domain/fact/index.js";

type AuthorityRole = "domain-choice" | "stable-identity" | "causal-observation" | "governance-authority";
type ActionOracleRoute = "public-edit" | "public-command" | "workspace-genesis";
type ActionFieldAuthority = {
  [Kind in AuthoredAction["kind"]]: Readonly<
    Record<Exclude<keyof Extract<AuthoredAction, Readonly<{ kind: Kind }>>, "kind">, AuthorityRole>
  >;
};

export const ACTION_ORACLE_ROUTE = {
  "field-configuration-set": "public-edit",
  "field-definition-make-discoverable": "public-edit",
  "field-definition-return-to-template-field": "public-edit",
  "field-materialize": "public-edit",
  "field-value-remove": "public-edit",
  "inline-alias-attach": "public-edit",
  "inline-alias-detach": "public-edit",
  "inline-reference-create": "public-edit",
  "inline-reference-remove": "public-edit",
  "materialized-field-clear": "public-edit",
  "node-create": "public-edit",
  "node-deletion-finalize": "public-command",
  "node-restore": "public-edit",
  "node-trash": "public-edit",
  "optional-field-contribution-add": "public-edit",
  "optional-field-contribution-remove": "public-edit",
  "original-promote": "public-edit",
  "placement-create": "public-edit",
  "placement-move": "public-edit",
  "placement-remove": "public-edit",
  "rich-text-mark": "public-edit",
  "rich-text-splice": "public-edit",
  "search-expression-add": "public-edit",
  "search-expression-configure": "public-edit",
  "search-expression-move": "public-edit",
  "search-expression-remove": "public-edit",
  "search-expression-restore": "public-edit",
  "shared-default-view-add": "public-edit",
  "shared-default-view-remove": "public-edit",
  "shared-default-view-restore": "public-edit",
  "supertag-application-add": "public-edit",
  "supertag-extension-add": "public-edit",
  "supertag-extension-remove": "public-edit",
  "supertag-membership-remove": "public-edit",
  "template-field-add": "public-edit",
  "template-field-remove": "public-edit",
  "template-field-restore": "public-edit",
  "template-field-static-default-set": "public-edit",
  "template-field-visibility-set": "public-edit",
  "template-member-add": "public-edit",
  "template-member-remove": "public-edit",
  "template-node-detach": "public-edit",
  "view-column-add": "public-edit",
  "view-column-move": "public-edit",
  "view-column-remove": "public-edit",
  "view-filter-add": "public-edit",
  "view-filter-remove": "public-edit",
  "view-filter-restore": "public-edit",
  "view-group-add": "public-edit",
  "view-group-remove": "public-edit",
  "view-mode-set": "public-edit",
  "view-sort-add": "public-edit",
  "view-sort-configure": "public-edit",
  "view-sort-remove": "public-edit",
  "view-sort-restore": "public-edit",
  "workspace-bootstrap": "workspace-genesis",
} as const satisfies Readonly<Record<AuthoredAction["kind"], ActionOracleRoute>>;

export const ACTION_FIELD_AUTHORITY = {
  "workspace-bootstrap": { workspaceNodeId: "stable-identity" },
  "node-create": {
    nodeId: "stable-identity",
    ownerNodeId: "stable-identity",
    originalPlacement: "domain-choice",
    intrinsicNodeType: "domain-choice",
    seed: "domain-choice",
  },
  "node-trash": { nodeId: "stable-identity" },
  "node-restore": {
    nodeId: "stable-identity",
    placementId: "stable-identity",
    parentNodeId: "stable-identity",
    anchor: "causal-observation",
  },
  "node-deletion-finalize": { nodeId: "stable-identity" },
  "original-promote": { nodeId: "stable-identity", placementId: "stable-identity" },
  "placement-create": {
    placementId: "stable-identity",
    nodeId: "stable-identity",
    parentNodeId: "stable-identity",
    anchor: "causal-observation",
  },
  "placement-remove": { placementId: "stable-identity" },
  "placement-move": {
    placementId: "stable-identity",
    parentNodeId: "stable-identity",
    anchor: "causal-observation",
  },
  "supertag-application-add": {
    hostNodeId: "stable-identity",
    supertagId: "stable-identity",
    anchor: "causal-observation",
  },
  "supertag-membership-remove": { hostNodeId: "stable-identity", supertagId: "stable-identity" },
  "supertag-extension-add": {
    supertagId: "stable-identity",
    baseSupertagId: "stable-identity",
    anchor: "causal-observation",
  },
  "supertag-extension-remove": { supertagId: "stable-identity", baseSupertagId: "stable-identity" },
  "template-member-add": {
    supertagId: "stable-identity",
    templateNodeId: "stable-identity",
    anchor: "causal-observation",
  },
  "template-member-remove": { supertagId: "stable-identity", templateNodeId: "stable-identity" },
  "template-field-add": {
    supertagId: "stable-identity",
    fieldDefinition: "domain-choice",
    anchor: "causal-observation",
  },
  "template-field-remove": { supertagId: "stable-identity", fieldDefinitionId: "stable-identity" },
  "template-field-restore": { templateFieldId: "stable-identity" },
  "template-field-visibility-set": { templateFieldId: "stable-identity", visibility: "domain-choice" },
  "template-field-static-default-set": { templateFieldId: "stable-identity", value: "domain-choice" },
  "optional-field-contribution-add": {
    supertagId: "stable-identity",
    fieldDefinitionId: "stable-identity",
    anchor: "causal-observation",
  },
  "optional-field-contribution-remove": { supertagId: "stable-identity", fieldDefinitionId: "stable-identity" },
  "template-node-detach": {
    ownerNodeId: "stable-identity",
    templateNodeId: "stable-identity",
    instanceNodeId: "stable-identity",
    instanceOccurrenceId: "stable-identity",
    anchor: "causal-observation",
  },
  "field-materialize": { ownerNodeId: "stable-identity", fieldDefinitionId: "stable-identity" },
  "field-value-remove": { valuePlacementId: "stable-identity" },
  "materialized-field-clear": { ownerNodeId: "stable-identity", fieldDefinitionId: "stable-identity" },
  "field-configuration-set": { fieldDefinitionId: "stable-identity", configuration: "domain-choice" },
  "field-definition-make-discoverable": { fieldDefinitionId: "stable-identity" },
  "field-definition-return-to-template-field": {
    fieldDefinitionId: "stable-identity",
    templateFieldId: "stable-identity",
  },
  "rich-text-splice": {
    nodeId: "stable-identity",
    deleteAtomIds: "causal-observation",
    anchor: "causal-observation",
    insert: "domain-choice",
    attributes: "domain-choice",
  },
  "rich-text-mark": {
    nodeId: "stable-identity",
    atomIds: "causal-observation",
    key: "domain-choice",
    value: "domain-choice",
  },
  "inline-reference-create": {
    inlineReferenceId: "stable-identity",
    hostNodeId: "stable-identity",
    targetNodeId: "stable-identity",
    anchor: "causal-observation",
  },
  "inline-reference-remove": { inlineReferenceId: "stable-identity" },
  "inline-alias-attach": { inlineReferenceId: "stable-identity", aliasNodeId: "stable-identity" },
  "inline-alias-detach": { inlineReferenceId: "stable-identity", aliasNodeId: "stable-identity" },
  "search-expression-add": {
    expressionHostId: "stable-identity",
    parentExpressionId: "stable-identity",
    clause: "domain-choice",
    anchor: "causal-observation",
  },
  "search-expression-configure": { expressionId: "stable-identity", clause: "domain-choice" },
  "search-expression-move": {
    expressionId: "stable-identity",
    parentExpressionId: "stable-identity",
    anchor: "causal-observation",
  },
  "search-expression-remove": { expressionId: "stable-identity" },
  "search-expression-restore": { expressionId: "stable-identity" },
  "shared-default-view-add": {
    hostNodeId: "stable-identity",
    viewType: "domain-choice",
    anchor: "causal-observation",
  },
  "shared-default-view-remove": { hostNodeId: "stable-identity" },
  "shared-default-view-restore": { viewId: "stable-identity" },
  "view-mode-set": { viewId: "stable-identity", viewType: "domain-choice" },
  "view-column-add": {
    viewId: "stable-identity",
    fieldDefinitionId: "stable-identity",
    anchor: "causal-observation",
  },
  "view-column-remove": { viewId: "stable-identity", fieldDefinitionId: "stable-identity" },
  "view-column-move": { columnId: "stable-identity", anchor: "causal-observation" },
  "view-sort-add": {
    viewId: "stable-identity",
    fieldDefinitionId: "stable-identity",
    direction: "domain-choice",
  },
  "view-sort-configure": {
    sortId: "stable-identity",
    fieldDefinitionId: "stable-identity",
    direction: "domain-choice",
  },
  "view-sort-remove": { viewId: "stable-identity" },
  "view-sort-restore": { sortId: "stable-identity" },
  "view-group-add": { viewId: "stable-identity", fieldDefinitionId: "stable-identity" },
  "view-group-remove": { viewId: "stable-identity" },
  "view-filter-add": { viewId: "stable-identity" },
  "view-filter-remove": { viewId: "stable-identity" },
  "view-filter-restore": { filterId: "stable-identity" },
} as const satisfies ActionFieldAuthority;
